package com.bhavanichandra.bisync.model;

public enum AccessoryTypes {
    BUTTON, OVERFLOW, STATIC_SELECT, USERS_SELECT, CONVERSATIONS_SELECT,
    CHANNELS_SELECT, EXTERNAL_SELECT, MULTI_STATIC_SELECT, MULTI_USERS_SELECT,
    MULTI_CONVERSATIONS_SELECT, MULTI_CHANNELS_SELECT, MULTI_EXTERNAL_SELECT,
    IMAGE, RADIO_BUTTONS, CHECKBOXES, DATEPICKER

}
