package com.bhavanichandra.bisync.model;

public enum ElementTypes {
    STATIC_SELECT,USERS_SELECT,CONVERSATIONS_SELECT,CHANNELS_SELECT,
    EXTERNAL_SELECT,BUTTON,OVERFLOW,DATEPICKER,RADIO_BUTTONS,CHECKBOXES,
    RANGE_DATEPICKER
}
